version = 1

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[analyzers]]
name = "test-coverage"
enabled = false

[[transformers]]
name = "prettier"
enabled = true